import React from "react";
import { AlertCircle, Zap, ShieldAlert, Info } from "lucide-react";

export const metadata = {
  title: "Disclaimer | QuickCap AI",
  description: "Important disclaimers regarding the accuracy and usage of QuickCap AI services.",
};

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-[#080A11] relative overflow-hidden">
      <div className="bg-mesh" />
      
      <main className="max-w-4xl mx-auto px-6 py-20 relative z-10">
        <div className="animate-fade-up">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-500 to-fuchsia-500 flex items-center justify-center shadow-lg shadow-violet-500/20">
              <AlertCircle className="w-6 h-6 text-white" />
            </div>
            <h1 className="text-4xl md:text-5xl font-black text-white tracking-tight">
              Legal <span className="text-gradient">Disclaimer</span>
            </h1>
          </div>
          
          <p className="text-slate-400 text-lg mb-12 max-w-2xl leading-relaxed">
            Please read this disclaimer carefully before using QuickCap AI. The information and services provided are subject to the following terms.
          </p>

          <div className="space-y-12">
            <section className="glass-premium p-8 rounded-3xl border border-white/5">
              <div className="flex items-center gap-4 mb-6">
                <div className="p-3 rounded-lg bg-violet-500/10 text-violet-400">
                  <Zap className="w-6 h-6" />
                </div>
                <h2 className="text-2xl font-bold text-white">AI Accuracy & Reliability</h2>
              </div>
              <p className="text-slate-300 leading-relaxed">
                QuickCap AI uses advanced artificial intelligence (Whisper) to generate captions. While we strive for high accuracy, the service is provided "as is" and "as available." AI models can make mistakes, hallucinate, or misinterpret audio due to background noise, accents, or technical issues. 
                <br /><br />
                <strong className="text-white">Users are solely responsible for reviewing and editing the generated captions for accuracy before final use.</strong>
              </p>
            </section>

            <section className="glass-premium p-8 rounded-3xl border border-white/5">
              <div className="flex items-center gap-4 mb-6">
                <div className="p-3 rounded-lg bg-pink-500/10 text-pink-400">
                  <ShieldAlert className="w-6 h-6" />
                </div>
                <h2 className="text-2xl font-bold text-white">No Professional Advice</h2>
              </div>
              <p className="text-slate-300 leading-relaxed">
                The content generated by QuickCap AI does not constitute legal, medical, or professional advice. QuickCap AI is not responsible for any decisions made based on the captions generated by our tool.
              </p>
            </section>

            <section className="glass-premium p-8 rounded-3xl border border-white/5">
              <div className="flex items-center gap-4 mb-6">
                <div className="p-3 rounded-lg bg-cyan-500/10 text-cyan-400">
                  <Info className="w-6 h-6" />
                </div>
                <h2 className="text-2xl font-bold text-white">External Links</h2>
              </div>
              <p className="text-slate-300 leading-relaxed">
                Our website may contain links to third-party websites or services (such as advertisements via Google AdSense). We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party sites.
              </p>
            </section>

            <section className="glass-premium p-8 rounded-3xl border border-white/5">
              <div className="flex items-center gap-4 mb-6">
                <div className="p-3 rounded-lg bg-blue-500/10 text-blue-400">
                  <AlertCircle className="w-6 h-6" />
                </div>
                <h2 className="text-2xl font-bold text-white">Changes to the Tool</h2>
              </div>
              <p className="text-slate-300 leading-relaxed">
                We reserve the right to modify, suspend, or discontinue any part of the service at any time without notice. We are not liable for any loss or damage resulting from these changes.
              </p>
              <p className="mt-4 text-slate-400 text-sm italic">Last Updated: May 4, 2026</p>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}
